//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCharacterSheetTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Character&gt;
        ///  &lt;Settings&gt;
        ///    &lt;Mute remember=&quot;true&quot; value=&quot;true&quot; /&gt;
        ///    &lt;Tab remember=&quot;false&quot; last=&quot;0&quot; /&gt;
        ///    &lt;AutoSave enabled=&quot;false&quot; interval=&quot;10&quot; /&gt;
        ///    &lt;AnimalCompanion hidden=&quot;true&quot; /&gt;
        ///    &lt;CoinWeight ignore=&quot;true&quot; /&gt;
        ///    &lt;Encumbrance use=&quot;false&quot; /&gt;
        ///  &lt;/Settings&gt;
        ///  &lt;Attributes&gt;
        ///    &lt;Strength value=&quot;7&quot; /&gt;
        ///    &lt;Dexterity value=&quot;20&quot; /&gt;
        ///    &lt;Constitution value=&quot;14&quot; /&gt;
        ///    &lt;Intelligence value=&quot;9&quot; /&gt;
        ///    &lt;Wisdom value=&quot;15&quot; /&gt;
        ///    &lt;Charisma value=&quot;16&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CalestonTest {
            get {
                return ResourceManager.GetString("CalestonTest", resourceCulture);
            }
        }
    }
}
